using System.Collections.Concurrent;
using System.Text.Json;
using System.Text.Json.Serialization;
using CallControl.Api.Services;

namespace CallControl.Api.Domain;

/// <summary>
/// Root configuration object for softphone, authentication, and PBX integration settings.
/// </summary>
public sealed class SoftphoneOptions
{
    /// <summary>
    /// Configuration section name used for binding this options model.
    /// </summary>
    public const string SectionName = "Softphone";

    /// <summary>
    /// JWT issuer value written into access tokens generated by this API.
    /// </summary>
    public string JwtIssuer { get; set; } = "CallControl.Api";

    /// <summary>
    /// JWT audience claim expected by the consuming web client.
    /// </summary>
    public string JwtAudience { get; set; } = "CallControl.WebClient";

    /// <summary>
    /// Secret key used to sign JWT access tokens.
    /// </summary>
    public string JwtSigningKey { get; set; } = "CHANGE_ME_TO_A_LONG_RANDOM_STRING";

    /// <summary>
    /// Access-token lifetime in minutes.
    /// </summary>
    public int TokenLifetimeMinutes { get; set; } = 720;

    /// <summary>
    /// Maximum number of websocket reconnect attempts before giving up.
    /// </summary>
    public int MaxWsReconnectAttempts { get; set; } = 8;

    /// <summary>
    /// Delay in seconds between websocket reconnect attempts.
    /// </summary>
    public int WsReconnectDelaySeconds { get; set; } = 3;

    /// <summary>
    /// PBX application credentials/settings used for 3CX API connectivity.
    /// </summary>
    public ThreeCxApiOptions ThreeCx { get; set; } = new();

    /// <summary>
    /// SIP-over-WebRTC global settings delivered to browser softphone clients.
    /// </summary>
    public SoftphoneSipWebRtcOptions SipWebRtc { get; set; } = new();

    /// <summary>
    /// Seed user credentials loaded from configuration for local/demo environments.
    /// </summary>
    public List<SoftphoneUserCredential> Users { get; set; } = [];
}

/// <summary>
/// Configuration-time credential and profile payload for a softphone user.
/// </summary>
public sealed class SoftphoneUserCredential
{
    /// <summary>
    /// Login username for local authentication.
    /// </summary>
    public string Username { get; set; } = string.Empty;

    /// <summary>
    /// Raw configured password used for local credential verification/bootstrap.
    /// </summary>
    public string Password { get; set; } = string.Empty;

    /// <summary>
    /// Given name shown in UI and activity logs.
    /// </summary>
    public string FirstName { get; set; } = string.Empty;

    /// <summary>
    /// Family name shown in UI and activity logs.
    /// </summary>
    public string LastName { get; set; } = string.Empty;

    /// <summary>
    /// Primary email address for notifications and account communication.
    /// </summary>
    public string EmailAddress { get; set; } = string.Empty;

    /// <summary>
    /// Default PBX extension/DN owned by the user.
    /// </summary>
    public string OwnedExtension { get; set; } = string.Empty;

    /// <summary>
    /// Optional explicit control DN used for call-control operations.
    /// </summary>
    public string? ControlDn { get; set; }

    /// <summary>
    /// Indicates whether this user should be provisioned as a supervisor.
    /// </summary>
    public bool IsSupervisor { get; set; }

    /// <summary>
    /// Preferred language code used for localization and prompt selection.
    /// </summary>
    public string Language { get; set; } = "EN";

    /// <summary>
    /// Optional prompt-set override for voicemail/audio assets.
    /// </summary>
    public string? PromptSet { get; set; }

    /// <summary>
    /// Voicemail email behavior option.
    /// </summary>
    public string VmEmailOptions { get; set; } = "Notification";

    /// <summary>
    /// Indicates whether missed-call email notifications are enabled.
    /// </summary>
    public bool SendEmailMissedCalls { get; set; } = true;

    /// <summary>
    /// Indicates whether two-factor authentication is required.
    /// </summary>
    public bool Require2Fa { get; set; }

    /// <summary>
    /// Enables or disables call-us chat integration for this user.
    /// </summary>
    public bool CallUsEnableChat { get; set; } = true;

    /// <summary>
    /// Optional external integration identifier for click-to-call features.
    /// </summary>
    public string? ClickToCallId { get; set; }

    /// <summary>
    /// Optional display-friendly identity for web meeting experiences.
    /// </summary>
    public string? WebMeetingFriendlyName { get; set; }

    /// <summary>
    /// Per-user SIP credentials used by WebRTC registration.
    /// </summary>
    public SoftphoneSipUserCredential Sip { get; set; } = new();
}

/// <summary>
/// Settings required to authenticate and connect to the 3CX integration APIs.
/// </summary>
public sealed class ThreeCxApiOptions
{
    /// <summary>
    /// Base URL of the target PBX instance.
    /// </summary>
    public string PbxBase { get; set; } = string.Empty;

    /// <summary>
    /// 3CX application/client identifier.
    /// </summary>
    public string AppId { get; set; } = string.Empty;

    /// <summary>
    /// 3CX application/client secret.
    /// </summary>
    public string AppSecret { get; set; } = string.Empty;
}

/// <summary>
/// Global WebRTC transport settings used by browser SIP clients.
/// </summary>
public sealed class SoftphoneSipWebRtcOptions
{
    /// <summary>
    /// Enables or disables SIP WebRTC registration support.
    /// </summary>
    public bool Enabled { get; set; }

    /// <summary>
    /// SIP websocket endpoint URL for registration and signaling.
    /// </summary>
    public string WebSocketUrl { get; set; } = string.Empty;

    /// <summary>
    /// SIP domain/realm used for address-of-record and authentication context.
    /// </summary>
    public string Domain { get; set; } = string.Empty;

    /// <summary>
    /// ICE server list supplied to the browser for media path negotiation.
    /// </summary>
    public List<string> IceServers { get; set; } = [];
}

/// <summary>
/// SIP identity and authentication details for a specific user.
/// </summary>
public sealed class SoftphoneSipUserCredential
{
    /// <summary>
    /// SIP address-of-record username.
    /// </summary>
    public string Username { get; set; } = string.Empty;

    /// <summary>
    /// SIP authorization username used in digest authentication.
    /// </summary>
    public string AuthId { get; set; } = string.Empty;

    /// <summary>
    /// SIP authorization password.
    /// </summary>
    public string Password { get; set; } = string.Empty;

    /// <summary>
    /// Caller/display name shown to other endpoints.
    /// </summary>
    public string DisplayName { get; set; } = string.Empty;
}

/// <summary>
/// API request payload used to authenticate a user session.
/// </summary>
public sealed class LoginRequest
{
    /// <summary>
    /// Username submitted by the caller.
    /// </summary>
    [JsonPropertyName("username")]
    public string Username { get; set; } = string.Empty;

    /// <summary>
    /// Password submitted by the caller.
    /// </summary>
    [JsonPropertyName("password")]
    public string Password { get; set; } = string.Empty;
}

/// <summary>
/// API response payload returned after successful authentication.
/// </summary>
public sealed class LoginResponse
{
    /// <summary>
    /// Internal numeric identifier of the authenticated user.
    /// </summary>
    [JsonPropertyName("userId")]
    public int UserId { get; init; }

    /// <summary>
    /// Signed access token used for subsequent authenticated requests.
    /// </summary>
    [JsonPropertyName("accessToken")]
    public string AccessToken { get; init; } = string.Empty;

    /// <summary>
    /// UTC expiration timestamp of the issued access token.
    /// </summary>
    [JsonPropertyName("expiresAtUtc")]
    public DateTimeOffset ExpiresAtUtc { get; init; }

    /// <summary>
    /// Server-side logical session identifier.
    /// </summary>
    [JsonPropertyName("sessionId")]
    public string SessionId { get; init; } = string.Empty;

    /// <summary>
    /// Authenticated username.
    /// </summary>
    [JsonPropertyName("username")]
    public string Username { get; init; } = string.Empty;

    /// <summary>
    /// Friendly display name shown in the client UI.
    /// </summary>
    [JsonPropertyName("displayName")]
    public string DisplayName { get; init; } = string.Empty;

    /// <summary>
    /// Role name exposed to the client for capability gating.
    /// </summary>
    [JsonPropertyName("role")]
    public string Role { get; init; } = AppUserRoles.User;

    /// <summary>
    /// Indicates whether the user can access softphone features.
    /// </summary>
    [JsonPropertyName("hasSoftphoneAccess")]
    public bool HasSoftphoneAccess { get; init; }

    /// <summary>
    /// DN/extension owned by the user and used as default call context.
    /// </summary>
    [JsonPropertyName("ownedExtensionDn")]
    public string OwnedExtensionDn { get; init; } = string.Empty;

    /// <summary>
    /// PBX base URL exposed to the client when it needs direct PBX-linked operations.
    /// </summary>
    [JsonPropertyName("pbxBase")]
    public string PbxBase { get; init; } = string.Empty;
}

/// <summary>
/// Client-facing SIP registration settings resolved for the current user.
/// </summary>
public sealed class SipRegistrationConfigResponse
{
    /// <summary>
    /// Indicates whether browser SIP registration is available.
    /// </summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; init; }

    /// <summary>
    /// SIP websocket URL to register/connect against.
    /// </summary>
    [JsonPropertyName("webSocketUrl")]
    public string WebSocketUrl { get; init; } = string.Empty;

    /// <summary>
    /// SIP domain/realm.
    /// </summary>
    [JsonPropertyName("domain")]
    public string Domain { get; init; } = string.Empty;

    /// <summary>
    /// Address-of-record username for SIP registration.
    /// </summary>
    [JsonPropertyName("aor")]
    public string Aor { get; init; } = string.Empty;

    /// <summary>
    /// Authorization username used for SIP digest authentication.
    /// </summary>
    [JsonPropertyName("authorizationUsername")]
    public string AuthorizationUsername { get; init; } = string.Empty;

    /// <summary>
    /// Authorization password used for SIP digest authentication.
    /// </summary>
    [JsonPropertyName("authorizationPassword")]
    public string AuthorizationPassword { get; init; } = string.Empty;

    /// <summary>
    /// Display name used by the SIP endpoint.
    /// </summary>
    [JsonPropertyName("displayName")]
    public string DisplayName { get; init; } = string.Empty;

    /// <summary>
    /// ICE server URLs provided to WebRTC for media connectivity.
    /// </summary>
    [JsonPropertyName("iceServers")]
    public List<string> IceServers { get; init; } = [];
}

/// <summary>
/// Request payload used to change the active extension context of a session.
/// </summary>
public sealed class SelectExtensionRequest
{
    /// <summary>
    /// Extension/DN to select for subsequent call operations.
    /// </summary>
    [JsonPropertyName("extensionDn")]
    public string ExtensionDn { get; set; } = string.Empty;
}

/// <summary>
/// Request payload used to set the active endpoint/device in a session.
/// </summary>
public sealed class SetActiveDeviceRequest
{
    /// <summary>
    /// Device identifier that should be used as active call target/control endpoint.
    /// </summary>
    [JsonPropertyName("deviceId")]
    public string DeviceId { get; set; } = string.Empty;
}

/// <summary>
/// Request payload for creating a new outbound call.
/// </summary>
public sealed class OutgoingCallRequest
{
    /// <summary>
    /// Destination DN/number/URI to call.
    /// </summary>
    [JsonPropertyName("destination")]
    public string Destination { get; set; } = string.Empty;
}

/// <summary>
/// Request payload for transferring an active call.
/// </summary>
public sealed class TransferRequest
{
    /// <summary>
    /// Transfer target DN/number/URI.
    /// </summary>
    [JsonPropertyName("destination")]
    public string Destination { get; set; } = string.Empty;
}

/// <summary>
/// Snapshot of the currently authenticated softphone session state.
/// </summary>
public sealed class SessionSnapshotResponse
{
    /// <summary>
    /// Indicates whether a valid softphone session is currently connected.
    /// </summary>
    [JsonPropertyName("connected")]
    public bool Connected { get; set; }

    /// <summary>
    /// Username bound to the current session.
    /// </summary>
    [JsonPropertyName("username")]
    public string Username { get; set; } = string.Empty;

    /// <summary>
    /// Server-side session identifier.
    /// </summary>
    [JsonPropertyName("sessionId")]
    public string SessionId { get; set; } = string.Empty;

    /// <summary>
    /// Optional currently selected extension context.
    /// </summary>
    [JsonPropertyName("selectedExtensionDn")]
    public string? SelectedExtensionDn { get; set; }

    /// <summary>
    /// User's owned/default extension.
    /// </summary>
    [JsonPropertyName("ownedExtensionDn")]
    public string OwnedExtensionDn { get; set; } = string.Empty;

    /// <summary>
    /// Optional control DN currently used for direct operations.
    /// </summary>
    [JsonPropertyName("controlDn")]
    public string? ControlDn { get; set; }

    /// <summary>
    /// Known devices discovered for the session context.
    /// </summary>
    [JsonPropertyName("devices")]
    public List<SoftphoneDeviceView> Devices { get; set; } = [];

    /// <summary>
    /// Currently active device identifier, if selected.
    /// </summary>
    [JsonPropertyName("activeDeviceId")]
    public string? ActiveDeviceId { get; set; }

    /// <summary>
    /// Active and recent call views for this session.
    /// </summary>
    [JsonPropertyName("calls")]
    public List<SoftphoneCallView> Calls { get; set; } = [];

    /// <summary>
    /// Indicates whether the backend websocket link to PBX events is connected.
    /// </summary>
    [JsonPropertyName("wsConnected")]
    public bool WsConnected { get; set; }

    /// <summary>
    /// UTC timestamp when the snapshot was last refreshed.
    /// </summary>
    [JsonPropertyName("lastUpdatedUtc")]
    public DateTimeOffset LastUpdatedUtc { get; set; }
}

/// <summary>
/// Lightweight view model describing a device endpoint associated with the user/session.
/// </summary>
public sealed class SoftphoneDeviceView
{
    /// <summary>
    /// DN/extension the device belongs to.
    /// </summary>
    [JsonPropertyName("dn")]
    public string? Dn { get; set; }

    /// <summary>
    /// PBX-provided unique device identifier.
    /// </summary>
    [JsonPropertyName("deviceId")]
    public string? DeviceId { get; set; }

    /// <summary>
    /// User-agent string identifying device type/software.
    /// </summary>
    [JsonPropertyName("userAgent")]
    public string? UserAgent { get; set; }
}

/// <summary>
/// Lightweight view model describing a call participant/call leg in the active session.
/// </summary>
public sealed class SoftphoneCallView
{
    /// <summary>
    /// Participant identifier used by the call-control API.
    /// </summary>
    [JsonPropertyName("participantId")]
    public long ParticipantId { get; set; }

    /// <summary>
    /// Local DN associated with this participant.
    /// </summary>
    [JsonPropertyName("dn")]
    public string? Dn { get; set; }

    /// <summary>
    /// Type/classification of the party DN.
    /// </summary>
    [JsonPropertyName("partyDnType")]
    public string? PartyDnType { get; set; }

    /// <summary>
    /// PBX call identifier, when available.
    /// </summary>
    [JsonPropertyName("callId")]
    public long? CallId { get; set; }

    /// <summary>
    /// PBX call-leg identifier, when available.
    /// </summary>
    [JsonPropertyName("legId")]
    public long? LegId { get; set; }

    /// <summary>
    /// Current participant/call state from PBX events.
    /// </summary>
    [JsonPropertyName("status")]
    public string? Status { get; set; }

    /// <summary>
    /// Remote party number/URI.
    /// </summary>
    [JsonPropertyName("remoteParty")]
    public string? RemoteParty { get; set; }

    /// <summary>
    /// Remote party display name.
    /// </summary>
    [JsonPropertyName("remoteName")]
    public string? RemoteName { get; set; }

    /// <summary>
    /// Direction of the call from the local user's perspective.
    /// </summary>
    [JsonPropertyName("direction")]
    public SoftphoneCallDirection Direction { get; set; }

    /// <summary>
    /// Indicates whether direct control actions are currently permitted.
    /// </summary>
    [JsonPropertyName("directControl")]
    public bool DirectControl { get; set; }

    /// <summary>
    /// Indicates whether this call can currently be answered.
    /// </summary>
    [JsonPropertyName("answerable")]
    public bool Answerable { get; set; }

    /// <summary>
    /// UTC timestamp when the call entered connected state.
    /// </summary>
    [JsonPropertyName("connectedAtUtc")]
    public DateTimeOffset? ConnectedAtUtc { get; set; }
}

/// <summary>
/// Generic outbound event envelope sent to clients over push channels.
/// </summary>
public sealed class SoftphoneEventEnvelope
{
    /// <summary>
    /// Event type name used for client-side dispatching.
    /// </summary>
    [JsonPropertyName("eventType")]
    public string EventType { get; set; } = string.Empty;

    /// <summary>
    /// UTC timestamp at which the event was emitted.
    /// </summary>
    [JsonPropertyName("occurredAtUtc")]
    public DateTimeOffset OccurredAtUtc { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Event-specific payload object.
    /// </summary>
    [JsonPropertyName("payload")]
    public object Payload { get; set; } = new();
}

/// <summary>
/// Immutable runtime connectivity settings used to construct a 3CX client instance.
/// </summary>
public sealed class ThreeCxConnectSettings
{
    /// <summary>
    /// Base URL of the PBX instance.
    /// </summary>
    public string PbxBase { get; init; } = string.Empty;

    /// <summary>
    /// Application identifier used for PBX API authentication.
    /// </summary>
    public string AppId { get; init; } = string.Empty;

    /// <summary>
    /// Application secret used for PBX API authentication.
    /// </summary>
    public string AppSecret { get; init; } = string.Empty;
}

/// <summary>
/// In-memory state holder for an active authenticated softphone session.
/// </summary>
/// <remarks>
/// This model aggregates topology snapshots, participant/device tracking, and synchronization primitives
/// needed for safe concurrent updates while handling PBX events and API commands.
/// </remarks>
public sealed class SoftphoneSession : IAsyncDisposable
{
    /// <summary>
    /// Unique logical session identifier.
    /// </summary>
    public required string SessionId { get; init; }

    /// <summary>
    /// Internal user identifier that owns this session.
    /// </summary>
    public required int AppUserId { get; init; }

    /// <summary>
    /// Username bound to this session.
    /// </summary>
    public required string Username { get; init; }

    /// <summary>
    /// Default owned extension for this session.
    /// </summary>
    public required string OwnedExtensionDn { get; init; }

    /// <summary>
    /// PBX connection settings used by <see cref="ThreeCxClient"/>.
    /// </summary>
    public required ThreeCxConnectSettings ConnectionSettings { get; init; }

    /// <summary>
    /// Active 3CX client used for API operations and websocket stream handling.
    /// </summary>
    public required ThreeCxCallControlClient ThreeCxClient { get; init; }

    /// <summary>
    /// Current topology indexed by DN for fast lookups and merges.
    /// </summary>
    public ConcurrentDictionary<string, ThreeCxDnInfoModel> TopologyByDn { get; } = new(StringComparer.Ordinal);

    /// <summary>
    /// Device inventory indexed by device identifier.
    /// </summary>
    public ConcurrentDictionary<string, ThreeCxDevice> Devices { get; } = new(StringComparer.Ordinal);

    /// <summary>
    /// Active/recent participants indexed by participant identifier.
    /// </summary>
    public ConcurrentDictionary<long, ThreeCxParticipant> Participants { get; } = new();

    /// <summary>
    /// Connected timestamps indexed by participant identifier.
    /// </summary>
    public ConcurrentDictionary<long, DateTimeOffset> ConnectedAtByParticipant { get; } = new();

    /// <summary>
    /// Direction snapshots indexed by participant identifier.
    /// </summary>
    public ConcurrentDictionary<long, SoftphoneCallDirection> DirectionByParticipant { get; } = new();

    /// <summary>
    /// Optional currently selected extension context.
    /// </summary>
    public string? SelectedExtensionDn { get; set; }

    /// <summary>
    /// Optional currently selected control DN override.
    /// </summary>
    public string? ControlDn { get; set; }

    /// <summary>
    /// Optional currently active device identifier.
    /// </summary>
    public string? ActiveDeviceId { get; set; }

    /// <summary>
    /// Indicates whether websocket connectivity to PBX event stream is active.
    /// </summary>
    public bool WsConnected { get; set; }

    /// <summary>
    /// UTC timestamp when the session object was created.
    /// </summary>
    public DateTimeOffset CreatedAtUtc { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// UTC timestamp when this session state was last changed.
    /// </summary>
    public DateTimeOffset LastUpdatedUtc { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Asynchronous gate used to serialize critical session mutations.
    /// </summary>
    public SemaphoreSlim Gate { get; } = new(1, 1);

    /// <summary>
    /// Releases session-owned resources, including synchronization gate and PBX client connection.
    /// </summary>
    public async ValueTask DisposeAsync()
    {
        Gate.Dispose();
        await ThreeCxClient.DisposeAsync();
    }
}

/// <summary>
/// Raw DN topology payload from 3CX APIs.
/// </summary>
public sealed class ThreeCxDnInfo
{
    /// <summary>
    /// DN/extension represented by this topology node.
    /// </summary>
    [JsonPropertyName("dn")]
    public string? Dn { get; set; }

    /// <summary>
    /// DN type classification (extension, queue, etc.).
    /// </summary>
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    /// <summary>
    /// Device collection attached to this DN.
    /// </summary>
    [JsonPropertyName("devices")]
    public List<ThreeCxDevice>? Devices { get; set; }

    /// <summary>
    /// Participant collection attached to this DN.
    /// </summary>
    [JsonPropertyName("participants")]
    public List<ThreeCxParticipant>? Participants { get; set; }
}

/// <summary>
/// Normalized in-memory DN topology model optimized for indexed lookup and mutation.
/// </summary>
public sealed class ThreeCxDnInfoModel
{
    /// <summary>
    /// DN/extension represented by the model.
    /// </summary>
    public string? Dn { get; set; }

    /// <summary>
    /// DN type classification.
    /// </summary>
    public string? Type { get; set; }

    /// <summary>
    /// Devices indexed by device identifier.
    /// </summary>
    public Dictionary<string, ThreeCxDevice> Devices { get; set; } = new(StringComparer.Ordinal);

    /// <summary>
    /// Participants indexed by participant identifier.
    /// </summary>
    public Dictionary<long, ThreeCxParticipant> Participants { get; set; } = new();
}

/// <summary>
/// 3CX device descriptor used in topology and participant references.
/// </summary>
public sealed class ThreeCxDevice
{
    /// <summary>
    /// DN that owns this device.
    /// </summary>
    [JsonPropertyName("dn")]
    public string? Dn { get; set; }

    /// <summary>
    /// 3CX unique device identifier.
    /// </summary>
    [JsonPropertyName("device_id")]
    public string? DeviceId { get; set; }

    /// <summary>
    /// User-agent label identifying the endpoint software/device.
    /// </summary>
    [JsonPropertyName("user_agent")]
    public string? UserAgent { get; set; }
}

/// <summary>
/// 3CX participant descriptor representing one party/leg within a call.
/// </summary>
public sealed class ThreeCxParticipant
{
    /// <summary>
    /// Participant identifier from 3CX.
    /// </summary>
    [JsonPropertyName("id")]
    [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)]
    public long? Id { get; set; }

    /// <summary>
    /// Current participant status.
    /// </summary>
    [JsonPropertyName("status")]
    public string? Status { get; set; }

    /// <summary>
    /// Remote caller name value when provided.
    /// </summary>
    [JsonPropertyName("party_caller_name")]
    public string? PartyCallerName { get; set; }

    /// <summary>
    /// Remote party DN/number/URI.
    /// </summary>
    [JsonPropertyName("party_dn")]
    public string? PartyDn { get; set; }

    /// <summary>
    /// Remote caller-id value.
    /// </summary>
    [JsonPropertyName("party_caller_id")]
    public string? PartyCallerId { get; set; }

    /// <summary>
    /// Device identifier associated with this participant leg.
    /// </summary>
    [JsonPropertyName("device_id")]
    public string? DeviceId { get; set; }

    /// <summary>
    /// Type/classification of the remote party DN.
    /// </summary>
    [JsonPropertyName("party_dn_type")]
    public string? PartyDnType { get; set; }

    /// <summary>
    /// Indicates whether direct control operations are allowed for this participant.
    /// </summary>
    [JsonPropertyName("direct_control")]
    public bool? DirectControl { get; set; }

    /// <summary>
    /// PBX call identifier.
    /// </summary>
    [JsonPropertyName("callid")]
    [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)]
    public long? CallId { get; set; }

    /// <summary>
    /// PBX leg identifier.
    /// </summary>
    [JsonPropertyName("legid")]
    [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)]
    public long? LegId { get; set; }

    /// <summary>
    /// Local DN associated with this participant.
    /// </summary>
    [JsonPropertyName("dn")]
    public string? Dn { get; set; }
}

/// <summary>
/// Response wrapper returned by 3CX call-control command endpoints.
/// </summary>
public sealed class ThreeCxCallControlResult
{
    /// <summary>
    /// Final numeric status code reported by 3CX for the command.
    /// </summary>
    [JsonPropertyName("finalstatus")]
    [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)]
    public long? FinalStatus { get; set; }

    /// <summary>
    /// Machine-readable reason code.
    /// </summary>
    [JsonPropertyName("reason")]
    public string? Reason { get; set; }

    /// <summary>
    /// Human-readable reason text.
    /// </summary>
    [JsonPropertyName("reasontext")]
    public string? ReasonText { get; set; }

    /// <summary>
    /// Participant payload returned as the operation result when applicable.
    /// </summary>
    [JsonPropertyName("result")]
    public ThreeCxParticipant? Result { get; set; }
}

/// <summary>
/// Wrapper model for websocket events emitted by 3CX.
/// </summary>
public sealed class ThreeCxWsEvent
{
    /// <summary>
    /// Monotonic sequence number for ordering/duplication handling.
    /// </summary>
    [JsonPropertyName("sequence")]
    [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)]
    public long Sequence { get; set; }

    /// <summary>
    /// Event body containing type and entity information.
    /// </summary>
    [JsonPropertyName("event")]
    public ThreeCxWsEventBody? Event { get; set; }
}

/// <summary>
/// Body model for a 3CX websocket event.
/// </summary>
public sealed class ThreeCxWsEventBody
{
    /// <summary>
    /// Domain event type emitted by 3CX.
    /// </summary>
    [JsonPropertyName("event_type")]
    public ThreeCxEventType EventType { get; set; }

    /// <summary>
    /// Entity identifier/path describing what changed.
    /// </summary>
    [JsonPropertyName("entity")]
    public string Entity { get; set; } = string.Empty;

    [JsonPropertyName("attached_data")]
    public JsonElement? AttachedData { get; set; }
}
