// <auto-generated />
using System;
using CallControl.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace pbx_demo_backend.Migrations
{
    [DbContext(typeof(PBXDbContext))]
    partial class PBXDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CallControl.Api.Domain.AppCallCdrEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("AnsweredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CallScopeId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("EndReason")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastStatusAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OperatorExtension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("OperatorUserId")
                        .HasColumnType("int");

                    b.Property<string>("OperatorUsername")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PbxCallId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PbxLegId")
                        .HasColumnType("bigint");

                    b.Property<string>("RemoteName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RemoteParty")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TrackingKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("OperatorUserId", "PbxCallId");

                    b.HasIndex("OperatorUserId", "StartedAtUtc");

                    b.HasIndex("Source", "TrackingKey");

                    b.ToTable("CallCdrs", (string)null);
                });

            modelBuilder.Entity("CallControl.Api.Domain.AppCallCdrStatusHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CallCdrId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventReason")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CallCdrId", "OccurredAtUtc");

                    b.ToTable("CallCdrStatusHistory", (string)null);
                });

            modelBuilder.Entity("CallControl.Api.Domain.AppDepartmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("DisableCustomPrompt")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("LiveChatLink")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LiveChatWebsite")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PromptSet")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PropsJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoutingJson")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThreeCxGroupId")
                        .HasColumnType("int");

                    b.Property<string>("ThreeCxGroupNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("ThreeCxWebsiteLinkId")
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ThreeCxGroupId")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("CallControl.Api.Domain.AppDepartmentMembershipEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppDepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ThreeCxRoleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AppDepartmentId");

                    b.HasIndex("AppUserId", "AppDepartmentId")
                        .IsUnique();

                    b.ToTable("DepartmentMemberships", (string)null);
                });

            modelBuilder.Entity("CallControl.Api.Domain.AppUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CallUsEnableChat")
                        .HasColumnType("bit");

                    b.Property<string>("ClickToCallId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ControlDn")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OwnedExtension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PromptSet")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Require2Fa")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("SendEmailMissedCalls")
                        .HasColumnType("bit");

                    b.Property<string>("SipAuthId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SipDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SipPassword")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SipUsername")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("ThreeCxUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("VmEmailOptions")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("WebMeetingFriendlyName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("OwnedExtension");

                    b.HasIndex("ThreeCxUserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.ExtensionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("ExtensionNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool?>("Internal")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRegistered")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastXapiSyncAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PbxUserId")
                        .HasColumnType("int");

                    b.Property<string>("QueueStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RawJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.HasIndex("ExtensionNumber")
                        .IsUnique();

                    b.HasIndex("PbxUserId")
                        .IsUnique();

                    b.HasIndex("QueueStatus");

                    b.ToTable("QueueExtension", (string)null);
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.OutboxMessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAtUtc", "Id");

                    b.HasIndex("Topic", "CreatedAtUtc");

                    b.ToTable("QueueOutboxMessage", (string)null);
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueAgentActivityEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActivityStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<long>("ExtensionId")
                        .HasColumnType("bigint");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("QueueCallId")
                        .HasColumnType("bigint");

                    b.Property<long?>("QueueId")
                        .HasColumnType("bigint");

                    b.Property<string>("RawJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("QueueCallId");

                    b.HasIndex("ExtensionId", "OccurredAtUtc");

                    b.HasIndex("QueueId", "OccurredAtUtc");

                    b.ToTable("QueueAgentActivity", (string)null);
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueAgentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AgentNumberSnapshot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("AssignmentSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("ExtensionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAgentMember")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsQueueManager")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastXapiSyncAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("PbxAgentRefId")
                        .HasColumnType("int");

                    b.Property<long>("QueueId")
                        .HasColumnType("bigint");

                    b.Property<string>("SkillGroup")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionId");

                    b.HasIndex("QueueId", "ExtensionId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("QueueId", "IsAgentMember");

                    b.HasIndex("QueueId", "IsDeleted");

                    b.HasIndex("QueueId", "IsQueueManager");

                    b.ToTable("QueueAgent", (string)null);
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueAnalyticsBucketDayEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AbandonedCalls")
                        .HasColumnType("bigint");

                    b.Property<long>("AnsweredCalls")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("BucketDate")
                        .HasColumnType("date");

                    b.Property<long>("MissedCalls")
                        .HasColumnType("bigint");

                    b.Property<long>("QueueId")
                        .HasColumnType("bigint");

                    b.Property<long>("SlaEligibleCalls")
                        .HasColumnType("bigint");

                    b.Property<long>("SlaWithinThresholdCalls")
                        .HasColumnType("bigint");

                    b.Property<long>("TalkingMsCount")
                        .HasColumnType("bigint");

                    b.Property<long>("TalkingMsSum")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("TotalCalls")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("WaitingMsCount")
                        .HasColumnType("bigint");

                    b.Property<long>("WaitingMsSum")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BucketDate", "QueueId");

                    b.HasIndex("QueueId", "BucketDate")
                        .IsUnique();

                    b.ToTable("QueueAnalyticsBucketDay", (string)null);
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueAnalyticsBucketHourEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AbandonedCalls")
                        .HasColumnType("bigint");

                    b.Property<long>("AnsweredCalls")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("BucketStartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("MissedCalls")
                        .HasColumnType("bigint");

                    b.Property<long>("QueueId")
                        .HasColumnType("bigint");

                    b.Property<long>("SlaEligibleCalls")
                        .HasColumnType("bigint");

                    b.Property<long>("SlaWithinThresholdCalls")
                        .HasColumnType("bigint");

                    b.Property<long>("TalkingMsCount")
                        .HasColumnType("bigint");

                    b.Property<long>("TalkingMsSum")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("TotalCalls")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("WaitingMsCount")
                        .HasColumnType("bigint");

                    b.Property<long>("WaitingMsSum")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BucketStartUtc", "QueueId");

                    b.HasIndex("QueueId", "BucketStartUtc")
                        .IsUnique();

                    b.ToTable("QueueAnalyticsBucketHour", (string)null);
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueCallEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("AbandonedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("AnsweredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("AnsweredByExtensionId")
                        .HasColumnType("bigint");

                    b.Property<string>("CallHistoryId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CalleeName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CalleeNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CallerName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CallerNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CdrId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CurrentSegmentId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Direction")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("EstablishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastAgentExtensionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MainCallHistoryId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("OfferedToAgentAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("PbxCallId")
                        .HasColumnType("int");

                    b.Property<long>("ProjectionVersion")
                        .HasColumnType("bigint");

                    b.Property<long?>("QueueId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("QueuedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RawCurrentJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RingingMs")
                        .HasColumnType("bigint");

                    b.Property<bool?>("SlaBreached")
                        .HasColumnType("bit");

                    b.Property<int?>("SlaThresholdSec")
                        .HasColumnType("int");

                    b.Property<long?>("TalkingMs")
                        .HasColumnType("bigint");

                    b.Property<int>("TransferCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("WaitOrder")
                        .HasColumnType("int");

                    b.Property<long?>("WaitingMs")
                        .HasColumnType("bigint");

                    b.Property<long?>("WrapUpMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AnsweredByExtensionId");

                    b.HasIndex("CdrId")
                        .HasFilter("[CdrId] IS NOT NULL");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("CorrelationKey");

                    b.HasIndex("LastAgentExtensionId");

                    b.HasIndex("PbxCallId")
                        .HasFilter("[PbxCallId] IS NOT NULL");

                    b.HasIndex("QueueId", "CurrentStatus");

                    b.HasIndex("QueueId", "QueuedAtUtc");

                    b.ToTable("QueueCall", (string)null);
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueCallEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EventAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("ExtensionId")
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalEventId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OrderingKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("PayloadHash")
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessingAttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long?>("QueueCallId")
                        .HasColumnType("bigint");

                    b.Property<long?>("QueueId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SequenceNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("QueueId");

                    b.HasIndex("ProcessingStatus", "NextAttemptAtUtc");

                    b.HasIndex("QueueCallId", "EventAtUtc");

                    b.HasIndex("OrderingKey", "EventAtUtc", "Id");

                    b.ToTable("QueueCallEvent", (string)null);
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueCallHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionDn")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ActionDnCallerId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActionDnDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("ActionDnType")
                        .HasColumnType("int");

                    b.Property<bool?>("CallAnswered")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CallCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CallHistoryId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("CallTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("CallType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CdrId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DestinationCallerId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DestinationDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DestinationDn")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("DestinationType")
                        .HasColumnType("int");

                    b.Property<string>("Direction")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MainCallHistoryId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("PbxCallId")
                        .HasColumnType("int");

                    b.Property<long?>("QueueCallId")
                        .HasColumnType("bigint");

                    b.Property<long?>("QueueId")
                        .HasColumnType("bigint");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RecordingUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<long?>("RingingDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int?>("SegmentActionId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SegmentEndAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("SegmentId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SegmentStartAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("SegmentType")
                        .HasColumnType("int");

                    b.Property<int?>("SentimentScore")
                        .HasColumnType("int");

                    b.Property<string>("SourceCallerId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SourceDn")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceRecordType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<int?>("SourceType")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("TalkingDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Transcription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CdrId");

                    b.HasIndex("PbxCallId");

                    b.HasIndex("QueueCallId");

                    b.HasIndex("QueueId", "SegmentStartAtUtc");

                    b.HasIndex("SourceRecordType", "CallHistoryId", "SegmentId");

                    b.HasIndex("SourceRecordType", "SegmentId", "CdrId");

                    b.ToTable("QueueCallHistory", (string)null);
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRegistered")
                        .HasColumnType("bit");

                    b.Property<byte[]>("LastXapiHash")
                        .HasColumnType("varbinary(32)");

                    b.Property<DateTimeOffset?>("LastXapiSyncAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("PbxQueueId")
                        .HasColumnType("int");

                    b.Property<string>("QueueNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RawJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.HasIndex("PbxQueueId")
                        .IsUnique();

                    b.HasIndex("QueueNumber")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Queue", (string)null);
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueScheduleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EffectiveFromDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveToDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("EndLocalTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<long>("QueueId")
                        .HasColumnType("bigint");

                    b.Property<string>("RuleJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<TimeSpan?>("StartLocalTime")
                        .HasColumnType("time");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("QueueId", "EffectiveFromDate", "EffectiveToDate");

                    b.HasIndex("QueueId", "ScheduleType", "IsEnabled");

                    b.ToTable("QueueSchedule", (string)null);
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueSettingsEntity", b =>
                {
                    b.Property<long>("QueueId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("AgentAvailabilityMode")
                        .HasColumnType("bit");

                    b.Property<bool?>("AnnounceQueuePosition")
                        .HasColumnType("bit");

                    b.Property<int?>("AnnouncementIntervalSec")
                        .HasColumnType("int");

                    b.Property<string>("BreakRouteJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("CallUsEnableChat")
                        .HasColumnType("bit");

                    b.Property<bool?>("CallUsEnablePhone")
                        .HasColumnType("bit");

                    b.Property<bool?>("CallUsEnableVideo")
                        .HasColumnType("bit");

                    b.Property<string>("CallUsRequirement")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("CallbackEnableTimeSec")
                        .HasColumnType("int");

                    b.Property<string>("CallbackPrefix")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ChatOwnershipType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ClickToCallId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool?>("EnableIntro")
                        .HasColumnType("bit");

                    b.Property<string>("ForwardNoAnswerJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GreetingFile")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("HolidaysRouteJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntroFile")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("MasterTimeoutSec")
                        .HasColumnType("int");

                    b.Property<int?>("MaxCallersInQueue")
                        .HasColumnType("int");

                    b.Property<string>("NotifyCodesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnHoldFile")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("OutOfOfficeRouteJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PlayFullPrompt")
                        .HasColumnType("bit");

                    b.Property<string>("PollingStrategy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool?>("PriorityQueue")
                        .HasColumnType("bit");

                    b.Property<string>("PromptSet")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RecordingMode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool?>("ResetStatisticsScheduleEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ResetStatsDayOfWeek")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ResetStatsFrequency")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ResetStatsTime")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("RingTimeoutSec")
                        .HasColumnType("int");

                    b.Property<int?>("SlaTimeSec")
                        .HasColumnType("int");

                    b.Property<string>("TranscriptionMode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("WrapUpTimeSec")
                        .HasColumnType("int");

                    b.HasKey("QueueId");

                    b.ToTable("QueueSettings", (string)null);
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueWaitingSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CallerName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CallerNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("EstimatedOrder")
                        .HasColumnType("bit");

                    b.Property<int?>("PbxCallId")
                        .HasColumnType("int");

                    b.Property<long?>("QueueCallId")
                        .HasColumnType("bigint");

                    b.Property<long>("QueueId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SnapshotKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WaitOrder")
                        .HasColumnType("int");

                    b.Property<long?>("WaitingMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("QueueCallId");

                    b.HasIndex("QueueId", "CapturedAtUtc");

                    b.HasIndex("QueueId", "SnapshotKey", "CorrelationKey")
                        .HasFilter("[CorrelationKey] IS NOT NULL");

                    b.HasIndex("QueueId", "SnapshotKey", "WaitOrder")
                        .IsUnique();

                    b.ToTable("QueueWaitingSnapshot", (string)null);
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueWebhookMappingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EndpointUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("EventTypesCsv")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("FilterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastDeliveryAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastFailureAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("QueueId")
                        .HasColumnType("bigint");

                    b.Property<string>("RetryPolicyJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretRef")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("WebhookEndpointId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WebhookEndpointId");

                    b.HasIndex("QueueId", "IsEnabled");

                    b.ToTable("QueueWebhookMapping", (string)null);
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.XapiSyncCheckpointEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CursorValue")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StreamName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("StreamName", "PartitionKey")
                        .IsUnique();

                    b.ToTable("XapiSyncCheckpoint", (string)null);
                });

            modelBuilder.Entity("CallControl.Api.Domain.AppCallCdrEntity", b =>
                {
                    b.HasOne("CallControl.Api.Domain.AppUserEntity", "OperatorUser")
                        .WithMany("CallCdrs")
                        .HasForeignKey("OperatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperatorUser");
                });

            modelBuilder.Entity("CallControl.Api.Domain.AppCallCdrStatusHistoryEntity", b =>
                {
                    b.HasOne("CallControl.Api.Domain.AppCallCdrEntity", "CallCdr")
                        .WithMany("StatusHistory")
                        .HasForeignKey("CallCdrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallCdr");
                });

            modelBuilder.Entity("CallControl.Api.Domain.AppDepartmentMembershipEntity", b =>
                {
                    b.HasOne("CallControl.Api.Domain.AppDepartmentEntity", "AppDepartment")
                        .WithMany("UserMemberships")
                        .HasForeignKey("AppDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CallControl.Api.Domain.AppUserEntity", "AppUser")
                        .WithMany("DepartmentMemberships")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppDepartment");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueAgentActivityEntity", b =>
                {
                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.ExtensionEntity", "Extension")
                        .WithMany()
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueCallEntity", "QueueCall")
                        .WithMany()
                        .HasForeignKey("QueueCallId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueEntity", "Queue")
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Extension");

                    b.Navigation("Queue");

                    b.Navigation("QueueCall");
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueAgentEntity", b =>
                {
                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.ExtensionEntity", "Extension")
                        .WithMany("QueueMemberships")
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueEntity", "Queue")
                        .WithMany("Agents")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Extension");

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueCallEntity", b =>
                {
                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.ExtensionEntity", "AnsweredByExtension")
                        .WithMany()
                        .HasForeignKey("AnsweredByExtensionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.ExtensionEntity", "LastAgentExtension")
                        .WithMany()
                        .HasForeignKey("LastAgentExtensionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueEntity", "Queue")
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AnsweredByExtension");

                    b.Navigation("LastAgentExtension");

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueCallEventEntity", b =>
                {
                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.ExtensionEntity", "Extension")
                        .WithMany()
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueCallEntity", "QueueCall")
                        .WithMany("Events")
                        .HasForeignKey("QueueCallId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueEntity", "Queue")
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Extension");

                    b.Navigation("Queue");

                    b.Navigation("QueueCall");
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueCallHistoryEntity", b =>
                {
                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueCallEntity", "QueueCall")
                        .WithMany("HistoryRows")
                        .HasForeignKey("QueueCallId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueEntity", "Queue")
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Queue");

                    b.Navigation("QueueCall");
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueScheduleEntity", b =>
                {
                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueEntity", "Queue")
                        .WithMany("Schedules")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueSettingsEntity", b =>
                {
                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueEntity", "Queue")
                        .WithOne("Settings")
                        .HasForeignKey("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueSettingsEntity", "QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueWaitingSnapshotEntity", b =>
                {
                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueCallEntity", "QueueCall")
                        .WithMany()
                        .HasForeignKey("QueueCallId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueEntity", "Queue")
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Queue");

                    b.Navigation("QueueCall");
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueWebhookMappingEntity", b =>
                {
                    b.HasOne("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueEntity", "Queue")
                        .WithMany("WebhookMappings")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("CallControl.Api.Domain.AppCallCdrEntity", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("CallControl.Api.Domain.AppDepartmentEntity", b =>
                {
                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("CallControl.Api.Domain.AppUserEntity", b =>
                {
                    b.Navigation("CallCdrs");

                    b.Navigation("DepartmentMemberships");
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.ExtensionEntity", b =>
                {
                    b.Navigation("QueueMemberships");
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueCallEntity", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("HistoryRows");
                });

            modelBuilder.Entity("pbx_demo_backend.Domain.QueueManagement.Contracts.QueueEntity", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Schedules");

                    b.Navigation("Settings");

                    b.Navigation("WebhookMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
